This code was written to create 50 binned classes for the data. The code must be changed accordingly to reflect the desired number of classes.

In [ ]:
import numpy as np
import tensorflow as tf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression


In [ ]:
freq_labelled = np.load('/content/drive/MyDrive/TIFR_internship /labelled.npy',allow_pickle = True,mmap_mode = 'r')
g_mode_spacing = np.load('/content/drive/MyDrive/TIFR_internship /param_2.npy',allow_pickle = True)

In [ ]:
g_mode_spacing

array([0.0510049 , 0.17810393, 0.10481929, ..., 0.15358216, 0.059644  ,
       0.05850256])

In [ ]:
g_max = np.max(g_mode_spacing)
g_min = np.min(g_mode_spacing)
g_min

0.01000320394110519

In [ ]:
g_max

0.3099978195151034

In [ ]:
g_range = np.linspace(g_min,g_max,50)
g_range

array([0.0100032 , 0.01612554, 0.02224788, 0.02837022, 0.03449256,
       0.0406149 , 0.04673724, 0.05285958, 0.05898192, 0.06510426,
       0.07122659, 0.07734893, 0.08347127, 0.08959361, 0.09571595,
       0.10183829, 0.10796063, 0.11408297, 0.12020531, 0.12632765,
       0.13244999, 0.13857232, 0.14469466, 0.150817  , 0.15693934,
       0.16306168, 0.16918402, 0.17530636, 0.1814287 , 0.18755104,
       0.19367338, 0.19979572, 0.20591805, 0.21204039, 0.21816273,
       0.22428507, 0.23040741, 0.23652975, 0.24265209, 0.24877443,
       0.25489677, 0.26101911, 0.26714145, 0.27326378, 0.27938612,
       0.28550846, 0.2916308 , 0.29775314, 0.30387548, 0.30999782])

In [ ]:
g_range_bins = np.empty([198004,50])
for i in range(0,198004):
    g_modes = g_mode_spacing
    initial_array = np.zeros(g_range.shape)
    diff = np.abs(g_range-g_modes[i])
    initial_array[np.argmin(diff)] = 1
    g_range_bins[i] = initial_array
g_range_bins

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

In [ ]:
np.save('/content/drive/MyDrive/TIFR_internship /binned_param_2_50.npy',g_range_bins,allow_pickle = True)